# 1. 다이나믹 프로그래밍

    * 메모리를 적절히 사용하여 수행 시간 효율성을 비약적으로 향상시키는 방법
    * 이미 계산된 결과는 별도의 메모리 영역에 저장 
    * 탑다운, 보텀업 방식으로 구성
    * 동적 계획법이라고도 부름. 
    * 1. 최적 부분 구조: 큰 문제를 작은 문제로 나눌 수 있으며 이 작은문제 답을 모아서 큰문제 해결
    * 2. 중복되는 부분문제: 동일한 작은 문제를 반복적으로 해결
    * ex) 피보나치 수열 점화식 

In [2]:
# 피보나치 단순 재귀코드 

def fibo(x):
    if x==1 or x==2:
        return 1
    return fibo(x-1) + fibo(x-2)
print(fibo(10))

# 이방법을 사용하면 동일한 부분문제가 반복되어 지수시간 복잡도를 가지게 됨
# 예를 들어 위 식에서 f(2) 는 매우 많이 반복 


55


# 2. 메모이제이션
    * 한번 계산된 결과를 메모리 공간에 메모하는 방법
    * 캐싱이라고 부르기도 함 (Cashing)
    * e다이나믹 프로그램의 전형적인 형태는 보텀업 방식 
    * 결과 저장용 리스트는 DP 테이블

In [5]:
# 피보나치 수열: 탑다운 다이나믹 프로그래밍 소스코드 

# 한번 계산된 결과를 메모이제이션 하기 위한 리스트 초기화

d = [0]*100

# 피보나치 함수를 재귀함수로 구현 (탑 다운 다이나믹 프로그래밍)

def fibo(x):
    # 종료조건 (1 혹은 2일 때 1을 반환)
    if x == 1 or x == 2:
        return 1 
    # 이미 계산한 적 있는 문제라면 그대로 반환
    if d[x] != 0:
        return d[x]
    # 아직 계산하지 않은 문제라면 점화식에 따라서 피보나치 결과 반환
    d[x] = fibo(x - 1)+ fibo(x - 2)
    return d[x]

print(fibo(99))

218922995834555169026


In [6]:
# 피보나치 수열: 보텀업 다이나믹 프로그래밍 소스코드 

d = [0]*100

# 첫 번째 두 번째 피보나치 수는 1
d[1] = 1
d[2] = 1
n = 99

# 피보나치 함수 반복문으로 구현 
for i in range(3, n+1):
    d[i] = d[i - 1] + d[i -2]

print(d[n])

# 시간복잡도는 O(N) 이 된다 

218922995834555169026


## 분할 정복 문제에서는 동일한 부분 문제가 반복되지 않는다는게 다이나믹과의 차이점

## 예시 -퀵정렬: 한 번 피벗이 자리를 변경해서 자리잡으면 다시 위치를 바꾸지 않는다. 


In [7]:
# 개미 전사 문제

# ai = i 번째 식량창고까지의 최적의 해 (식량 최댓값)
# ki = i 번째 식량창고에 있는 식량의 양

# i번째 식량창고 털지 말지에 따라 달라짐
# 현재 식량창고 털면 i-2의 최댓값 + 현재 식량 창고
# 현재 식량창고 안털면 i-1까지의 최댓값
# ai = max(ai-1, ai-2 + ki)

n= int(input())
array = list(map(int, input().split()))

d = [0]*100
d[0] = array[0]
d[1] = max(array[0], array[1])
for i in range(2, n):
    d[i] = max(d[i -1], d[i -2]+ array[i])

print(d[n-1])

5
2 4 1 2 5
9


In [21]:
# 정수를 1로 만들기 

x = int(input())

d= [0] * 30001

d[0] = 30000
d[1] = 0
d[2] = 1
for i in range (3, x + 1):
    temp = [0] * 4
    if i % 5 == 0:
        temp[0] = (i // 5)
    if i % 3 == 0:
        temp[1] = (i // 3)
    if i % 2 == 0:
        temp[2] = (i // 2)
    temp[3]= (i - 1)
    d[i] = min(d[temp[0]], d[temp[1]], d[temp[2]], d[temp[3]]) + 1 
    
print(d[x])
    

30000
8


In [93]:
# 효율적인 화폐구성 

# n, m = map(int, input().split())
# array = list(map(int, input().split()))
n = 5
m = 11
array = [3, 5, 8, 9, 12]
array.sort()
from bisect import bisect_left, bisect_right


d = [0]* 10001

for i in range(1, min(array)):
    d[i] = -1 

for i in range(min(array), m+1):
    oneminus = list(d[i -array[j]] for j in range(bisect_right(array, i)))
    if set(oneminus) == {-1}:
        d[i] = -1
    elif -1 in oneminus:
        oneminus = list(set(oneminus))
        oneminus.remove(-1)
        d[i] = min(oneminus) + 1
    else: d[i] = min(oneminus) + 1
        
print(d[m])

2


In [135]:
# 금광 채굴 문제 실패

# t = int(input())
# n, m = map(int, input().split())
# array = list(map(int, input().split()))

# t = 2
# n = 3 
# m = 4
# array = [1, 3, 3, 2, 2, 1, 4, 1, 0, 6, 4, 7]
# newarray= list()
# matarray= list()
# for i in range(n):
#     for j in range(1, m+1):
#         newarray.append(array[i * m + j - 1])
#     matarray.append(newarray)
#     newarray = list()
# print(matarray)    
    
# import numpy as np

# h = np.array(matarray)
# print(h)
# testindex= list(h[:,0]).index(t)
# print(testindex)

# d = [0]* (n*m + 1)

# for i in range(n):
#     d[(i+1)*m] = h[i][m-1]
# print(d)
 
# def loop(a, b):
#     list1=list()
#     for i in (a -1, a +2):
#         if i<0 or i>=n:
#             list1.append(0)
#         else:
#             list1.append(loop(i, b+1))
#     d[a*m + b+1] = max(list1) + h[a][b]
#     return d[a*m + b+1]
    
# loop(testindex, 0)        

In [136]:
#  금광문제 정답 나오는 풀이 
import numpy as np
T = 2 # 시
n = 3 # 행
m = 4 # 열

gold_M = np.array([[1, 3, 3, 2], [2, 1, 4, 1], [0, 6, 4, 7]])
print('gold:\n', gold_M)

sum_M = np.zeros([n, m])

# Initialize the first column
sum_M[:, 0] = [1, 2, 0]
print(sum_M)
for j in range(1, m):
    for i in range(n):
        left = sum_M[i][j - 1]
        if i - 1 >= 0:
            left_up = sum_M[i - 1][j - 1]
        else:
            left_up = 0
        if i + 1 < n:
            left_down = sum_M[i + 1][j - 1]
        else:
            left_down = 0
        # print(i, j, left, left_up, left_down)
        sum_M[i][j] = gold_M[i][j] + max(left, left_up, left_down)


print(sum_M)
print(int(max(sum_M[:, -1])))

gold:
 [[1 3 3 2]
 [2 1 4 1]
 [0 6 4 7]]
[[1. 0. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 1.  5.  8. 14.]
 [ 2.  3. 12. 13.]
 [ 0.  8. 12. 19.]]
19


In [ ]:
# 병사 배치하기 문제 