In [73]:
import tensorflow as tf
tf.random.set_seed(777)
import numpy as np

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
x_data = np.asarray(x_data, dtype = np.float32)  #numpy 형태로 변환시킴
y_data = np.asarray(y_data, dtype = np.float32 )
nb_classes = 3
print(x_data)
print(y_data)

[[1. 2. 1. 1.]
 [2. 1. 3. 2.]
 [3. 1. 3. 4.]
 [4. 1. 5. 5.]
 [1. 7. 5. 5.]
 [1. 2. 5. 6.]
 [1. 6. 6. 6.]
 [1. 7. 7. 7.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [74]:
W = tf.Variable(tf.random.normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random.normal([nb_classes]), name = 'bias')
variables = [W, b]
print(W, b)

<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.7706481 ,  0.37335402, -0.05576323],
       [ 0.00358377, -0.5898363 ,  1.5702795 ],
       [ 0.2460895 , -0.09918973,  1.4418385 ],
       [ 0.3200988 ,  0.526784  , -0.7703731 ]], dtype=float32)> <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([-1.3080608 , -0.13253094,  0.5513761 ], dtype=float32)>


In [75]:
def hypothesis(X) :
    return tf.nn.softmax(tf.matmul(X,W) + b)

print(hypothesis(x_data))

tf.Tensor(
[[1.36571955e-02 7.90162385e-03 9.78441238e-01]
 [3.92598137e-02 1.70347560e-02 9.43705440e-01]
 [3.80385250e-01 1.67723224e-01 4.51891541e-01]
 [3.23390484e-01 5.90759404e-02 6.17533624e-01]
 [3.62997412e-06 6.20727292e-08 9.99996305e-01]
 [2.62520462e-02 1.07279727e-02 9.63019967e-01]
 [1.56525111e-05 4.21802781e-07 9.99983907e-01]
 [2.94077745e-06 3.81134022e-08 9.99997020e-01]], shape=(8, 3), dtype=float32)


In [76]:
# Softmax one hot test
sample_db = [[8, 2, 1, 4]]
sample_db = np.asarray(sample_db, dtype =np.float32)
print(hypothesis(sample_db))

tf.Tensor([[0.9302204  0.06200533 0.00777428]], shape=(1, 3), dtype=float32)


In [77]:
# cost function
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis =1)
    cost_mean = tf.reduce_mean(cost)
    return cost_mean
print(cost_fn(x_data, y_data))

tf.Tensor(6.07932, shape=(), dtype=float32)


In [78]:
# Gradient function
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        cost = cost_fn(X, Y)
        grads = tape.gradient(cost, variables)
        return grads
print(grad_fn(x_data, y_data))

[<tf.Tensor: id=964963, shape=(4, 3), dtype=float32, numpy=
array([[ 0.06914611, -0.6509784 ,  0.5818323 ],
       [-1.5221257 , -1.214863  ,  2.7369888 ],
       [-1.2473828 , -1.7611002 ,  3.008483  ],
       [-1.2014606 , -1.865923  ,  3.0673838 ]], dtype=float32)>, <tf.Tensor: id=964962, shape=(3,), dtype=float32, numpy=array([-0.15212911, -0.342192  ,  0.4943211 ], dtype=float32)>]


In [79]:
# Train 시키기 
def fit(X, Y, epochs=5000, verbose=100):
    optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)
    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            
fit(x_data, y_data)

Loss at epoch 1: 2.849417
Loss at epoch 100: 0.684151
Loss at epoch 200: 0.613813
Loss at epoch 300: 0.558204
Loss at epoch 400: 0.508305
Loss at epoch 500: 0.461059
Loss at epoch 600: 0.415072
Loss at epoch 700: 0.369636
Loss at epoch 800: 0.324533
Loss at epoch 900: 0.280721
Loss at epoch 1000: 0.246752
Loss at epoch 1100: 0.232798
Loss at epoch 1200: 0.221645
Loss at epoch 1300: 0.211476
Loss at epoch 1400: 0.202164
Loss at epoch 1500: 0.193606
Loss at epoch 1600: 0.185714
Loss at epoch 1700: 0.178415
Loss at epoch 1800: 0.171645
Loss at epoch 1900: 0.165350
Loss at epoch 2000: 0.159483
Loss at epoch 2100: 0.154003
Loss at epoch 2200: 0.148872
Loss at epoch 2300: 0.144060
Loss at epoch 2400: 0.139539
Loss at epoch 2500: 0.135283
Loss at epoch 2600: 0.131269
Loss at epoch 2700: 0.127480
Loss at epoch 2800: 0.123896
Loss at epoch 2900: 0.120501
Loss at epoch 3000: 0.117282
Loss at epoch 3100: 0.114226
Loss at epoch 3200: 0.111319
Loss at epoch 3300: 0.108553
Loss at epoch 3400: 0.1059

In [80]:
# Prediction

a = hypothesis(x_data)

print(a)
print(tf.argmax(a,1)) # 예측 
print(tf.argmax(y_data, 1)) # 실제 정답

# argmax(a,0)은 각 열 기준 가장 큰 값 갖는 인덱스를 반환
# argmax(a,1)은 각 행 기준 가장 큰 값 갖는 인덱스를 반환

tf.Tensor(
[[6.6137580e-09 7.2284871e-05 9.9992776e-01]
 [3.2846202e-04 3.7847254e-02 9.6182424e-01]
 [1.4289739e-10 7.9331651e-02 9.2066836e-01]
 [7.4088604e-08 9.2845166e-01 7.1548261e-02]
 [1.3415068e-01 8.6033237e-01 5.5169621e-03]
 [7.1083315e-02 9.2891544e-01 1.1928440e-06]
 [8.4745944e-01 1.5253913e-01 1.4169254e-06]
 [9.7736520e-01 2.2634877e-02 3.9788888e-09]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


In [81]:
# Zoo_classifier example

xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, -1]

nb_classes = 7  # 0 ~ 6


# Make Y data as onehot shape
# 기존에 1차원 벡터였던 (101,1)형태에서 (101,7) 형태로 랭크 하나 올라감

Y_one_hot = tf.one_hot(y_data.astype(np.int32), nb_classes)

print(x_data.shape, Y_one_hot.shape)

(101, 16) (101, 7)


In [82]:
#Weight and bias setting

W = tf.Variable(tf.random.normal((16, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
variables = [W, b]

# 이번에는 내장된 함수 softmax사용해서 함수들 정의
# 여기서 사실상 logits만 필요하고 hypothesis 는 없어도 된다. 
# 그러나 뒤에서 prediction 비교부분에서 필요해서 일단 정의해줌

def logit_fn(X):
    return tf.matmul(X, W) + b

def hypothesis(X):
    return tf.nn.softmax(logit_fn(X))


#d 아래 cost fuction에는 hypothesis 대신 logit을 넣어줌 
def cost_fn(X, Y):
    logits = logit_fn(X)
    cost_i = tf.keras.losses.categorical_crossentropy(y_true=Y, y_pred=logits, 
                                                      from_logits=True)    
    cost = tf.reduce_mean(cost_i)    
    return cost

def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables)
        return grads
    
def prediction(X, Y):
    pred = tf.argmax(hypothesis(X), 1)
    correct_prediction = tf.equal(pred, tf.argmax(Y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

    return accuracy

In [83]:
def fit(X, Y, epochs=1000, verbose=100):
    optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
# print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            acc = prediction(X, Y).numpy()
            loss = cost_fn(X, Y).numpy() 
            print('Steps: {} Loss: {}, Acc: {}'.format(i+1, loss, acc))

fit(x_data, Y_one_hot)

Steps: 1 Loss: 5.610101222991943, Acc: 0.1683168262243271
Steps: 100 Loss: 0.6019306182861328, Acc: 0.8415841460227966
Steps: 200 Loss: 0.38190871477127075, Acc: 0.9108911156654358
Steps: 300 Loss: 0.2877010405063629, Acc: 0.9405940771102905
Steps: 400 Loss: 0.23101475834846497, Acc: 0.9504950642585754
Steps: 500 Loss: 0.19246312975883484, Acc: 0.9603960514068604
Steps: 600 Loss: 0.16442006826400757, Acc: 0.9603960514068604
Steps: 700 Loss: 0.14311201870441437, Acc: 0.9603960514068604
Steps: 800 Loss: 0.12642517685890198, Acc: 0.9603960514068604
Steps: 900 Loss: 0.11306188255548477, Acc: 0.9900990128517151
Steps: 1000 Loss: 0.10216664522886276, Acc: 0.9900990128517151
